feat: zip tasks load and display
mini-maxit/frontend-archive pull request #1
Opened 2024-10-21 17:28 UTC by TheRealSeber

2024-10-21 20:40 UTC, HermanPlay requested changes

2024-10-21 20:40 UTC, HermanPlay commented on src/lib/components/taskFile.svelte.ts
> +		const outFileName = outFiles.find((file) => file.name === inFileName.replaceAll('in', 'out'));
replaceAll strategy doesnt work if path contains "in". Forexample: _inversions/in/in4.txt_. After replace we have: _outversions/out/out4.txt_

2024-10-28 01:51 UTC, TheRealSeber commented on src/lib/components/taskFile.svelte.ts
> +		const outFileName = outFiles.find((file) => file.name === inFileName.replaceAll('in', 'out'));
bruh

2024-11-03 22:01 UTC, HermanPlay commented on src/lib/server/db/schema.ts
> +	userSolutionId: integer('user_solution_id').references(() => submissions.id),
userSolutionId -> submissionId

2024-11-03 22:02 UTC, HermanPlay commented on src/lib/server/db/schema.ts
> +	userSolutionResultId: integer('user_solution_result_id').references(() => submissionResults.id),
userSolutionResultId -> submissionResultId

2024-11-03 22:03 UTC, HermanPlay commented on src/lib/server/db/schema.ts
> +	userSolutionId: integer('user_solution_id').references(() => submissions.id),
userSolutionId -> submissionId

2024-11-03 22:03 UTC, HermanPlay commented on src/lib/server/db/schema.ts
> +export const userSolutionStatusEnum = pgEnum('user_solution_status', [
userSolutionStatusEnum -> submissionStatusEnum

2024-11-03 22:03 UTC, HermanPlay commented on src/lib/server/db/schema.ts
> +export const userSolutionResultStatusEnum = pgEnum('user_solution_result_status', [
userSolutionResultStatusEnum -> submissionResultStatusEnum

2024-11-07 10:31 UTC, HermanPlay approved these changes

2024-11-07 10:33 UTC, merged